### ISSUE TITLE
Alphabetical ordering breaks with hyphen keys

### ISSUE THREAD

**Issue by mbohgard** [seiyab/prettier-plugin-sort-members#34]
Given `"sortMembersAlphabetically": true`, plugin formats code like this:
```ts
export type DataEndpoints = {
  user: Endpoint<UserResponse>;
  'repair-orders': Endpoint<RepairOrdersResponse>;
};
```
where `user` should be sorted below 'repair-orders'

**Comment by seiyab** [comment]
That's true. It's a bug (or lacking feature). I'll investigate it.

**Comment by seiyab** [comment]
@mbohgard Would you try version 0.1.1?

**Comment by seiyab** [comment]
Version 0.1.1 should resolve this. Close this anyway. Tell me if you still have this problem or see other issues. Thank you for feedback!
